include: '../snakemake/conf.sk'


rule all:
    input: expand(DATA_DIR + "/" + ASSEMBLY + "_{len}/{chrom}_{len}_frags", chrom=CHROMOSOMES, len=READLEN),
           expand(DATA_DIR + "/{k}mer_dictionary", k=K)

#filter chromosomes (keep chr1-22,X,Y)
#samtools faidx {input} chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY > local/share/data/GRCh38.fa

rule split_chrom: #Split reference genome fasta by chromosome
    input:ASSEMBLY_FA
    output:expand(CHROM_DIR + "/{chrom}.fa", chrom=CHROMOSOMES)
    params: outdir=CHROM_DIR
    shell:
        """
            if [ ! -d {params.outdir}]; then
                mkdir -p {params.outdir}
            fi

            faSplit byname  {input} {params.outdir}
        """

rule split_genome: #Simulating $len bp Reads
    input: CHROM_DIR + "/{chrom}.fa"
    output: DATA_DIR + "/" + ASSEMBLY + "_{len}/{chrom}_{len}_frags"
    params: tool=BIN_DIR+"/simReads", outdir=DATA_DIR + "/" + ASSEMBLY + "_{len}"
    shell:
        """
        if [ ! -d {params.outdir} ]; then
            mkdir -p {params.outdir}
        fi

        {params.tool} {input} {output} {wildcards.len}
        """

rule make_kmer_list: #generating dictionary of kmers for different values of K
    output: DATA_DIR + "/{k}mer_dictionary"
    params: alphabet=ALPHABET, tool=MK_KMERS_DICT, outdir=DATA_DIR
    shell:
        """
        python {params.tool} -k {wildcards.k} -a {params.alphabet} -o {params.outdir}
        """

